version: '3.7'
networks:
  docker_network:
services:
  PHP-SRV:
    image: php7.4
    container_name: php7.4
    volumes:
      - .:/var/www/html
      - ./../../configs/99-xdebug.ini:/usr/local/etc/php/conf.d/99-xdebug.ini
      - ./../../configs/apache2.conf:/etc/apache2/apache2.conf
      #- ~/work/docker/ex3/config/php.ini:/usr/local/etc/php/php.ini
    networks:
      - docker_network 
    ports: 
      - '8080:80'
  MYSQL:
    image: mysql:5.7-debian
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - docker_network 
    environment:
      - MYSQL_ROOT_PASSWORD=root
  PMA:
    image: phpmyadmin
    networks:
      - docker_network 
    ports: 
      - '8090:80'
    environment:
      - PMA_HOST=MYSQL
      - UPLOAD_LIMIT=1G